// Application routes constants

export const ROUTES = {
  // Public routes
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',

  // Super Admin routes
  SUPER_ADMIN: {
    DASHBOARD: '/super-admin',
    SCHOOLS: '/super-admin/schools',
    SCHOOLS_CREATE: '/super-admin/schools/create',
    SCHOOLS_EDIT: (id: string) => `/super-admin/schools/${id}/edit`,
    SCHOOLS_VIEW: (id: string) => `/super-admin/schools/${id}`,
    USERS: '/super-admin/users',
    USERS_CREATE: '/super-admin/users/create',
    USERS_EDIT: (id: string) => `/super-admin/users/${id}/edit`,
    SUBSCRIPTIONS: '/super-admin/subscriptions',
    SUBSCRIPTIONS_CREATE: '/super-admin/subscriptions/create',
    SUBSCRIPTIONS_EDIT: (id: string) => `/super-admin/subscriptions/${id}/edit`,
    SUBSCRIPTION_REQUESTS: '/super-admin/subscription-requests',
    SETTINGS: '/super-admin/settings',
  },

  // Admin (School Admin) routes
  ADMIN: {
    DASHBOARD: '/admin',
    SESSIONS: '/admin/sessions',
    SESSIONS_CREATE: '/admin/sessions/create',
    SESSIONS_EDIT: (id: string) => `/admin/sessions/${id}/edit`,
    CLASSES: '/admin/classes',
    CLASSES_CREATE: '/admin/classes/create',
    CLASSES_EDIT: (id: string) => `/admin/classes/${id}/edit`,
    CLASSES_VIEW: (id: string) => `/admin/classes/${id}`,
    STUDENTS: '/admin/students',
    STUDENTS_CREATE: '/admin/students/create',
    STUDENTS_EDIT: (id: string) => `/admin/students/${id}/edit`,
    STUDENTS_VIEW: (id: string) => `/admin/students/${id}`,
    STUDENTS_PROMOTE: '/admin/students/promote',
    STUDENTS_DEMOTE: '/admin/students/demote',
    STUDENTS_ID_CARDS: '/admin/students/id-cards',
    FEES: {
      SETTINGS: '/admin/fees/settings',
      GENERATE: '/admin/fees/generate',
      VIEW: '/admin/fees',
      COLLECT: '/admin/fees/collect',
      HISTORY: '/admin/fees/history',
      STUDENT: (studentId: string) => `/admin/fees/students/${studentId}`,
    },
    SALARIES: {
      GENERATE: '/admin/salaries/generate',
      VIEW: '/admin/salaries',
      PAY: '/admin/salaries/pay',
      HISTORY: '/admin/salaries/history',
      STAFF: (staffId: string) => `/admin/salaries/staff/${staffId}`,
    },
    SALARY_POLICIES: {
      OVERVIEW: '/admin/salary-policies/overview',
      SECURITY_DEDUCTION: '/admin/salaries/policies/security-deduction',
      LEAVE_DEDUCTION: '/admin/salaries/policies/leave-deduction',
    },
    SECTIONS: '/admin/sections',
    SECTIONS_CREATE: '/admin/sections/create',
    SECTIONS_EDIT: (id: string) => `/admin/sections/${id}/edit`,
    SECTIONS_VIEW: (id: string) => `/admin/sections/${id}`,
    SUBJECTS: '/admin/subjects',
    SUBJECTS_CREATE: '/admin/subjects/create',
    SUBJECTS_EDIT: (id: string) => `/admin/subjects/${id}/edit`,
    SUBJECTS_VIEW: (id: string) => `/admin/subjects/${id}`,
    TIMETABLES: '/admin/timetables',
    TIMETABLES_CREATE: '/admin/timetables/create',
    TIMETABLES_EDIT: (id: string) => `/admin/timetables/${id}/edit`,
    TIMETABLES_VIEW: (id: string) => `/admin/timetables/${id}`,
    STAFF: '/admin/staff',
    STAFF_CREATE: '/admin/staff/create',
    STAFF_EDIT: (id: string) => `/admin/staff/${id}/edit`,
    STAFF_VIEW: (id: string) => `/admin/staff/${id}`,
    STAFF_LEAVES: '/admin/staff/leaves',
    STAFF_LEAVES_TYPES: '/admin/staff/leaves/types',
    STAFF_LEAVES_REQUESTS: '/admin/staff/leaves/requests',
    STAFF_LEAVES_HISTORY: '/admin/staff/leaves/history',
    STAFF_WORK_CALENDAR: '/admin/staff/work-calendar',
    STAFF_ID_CARDS: '/admin/staff/id-cards',
    STAFF_WORK_CALENDAR_BY_ID: (id: string) => `/admin/staff/${id}/work-calendar`,
    ADMINISTRATION: {
      SCHOOL: '/admin/administration/school',
      CAMPUSES: '/admin/administration/campuses',
      CAMPUSES_CREATE: '/admin/administration/campuses/create',
      CAMPUSES_EDIT: (id: string) => `/admin/administration/campuses/${id}/edit`,
      ADMINS: '/admin/administration/admins',
      ADMINS_CREATE: '/admin/administration/admins/create',
      ADMINS_EDIT: (id: string) => `/admin/administration/admins/${id}/edit`,
      EVENT_CALENDAR: '/admin/administration/event-calendar',
    },
    SETTINGS: '/admin/settings',
    /** School admin: current plan & included features (read-only) */
    SUBSCRIPTION: '/admin/subscription',
    NOTIFICATIONS: '/admin/notifications',
    ATTENDANCE: {
      STUDENTS: '/admin/attendance/students',
      STAFF: '/admin/attendance/staff',
      TEACHERS: '/admin/attendance/teachers',
      STUDENT_HISTORY: (studentId: string) => `/admin/attendance/students/${studentId}/history`,
      STAFF_HISTORY: (staffId: string) => `/admin/attendance/staff/${staffId}/history`,
    },
    EXPENSES: '/admin/expenses',
    EXPENSES_CREATE: '/admin/expenses/create',
    EXPENSES_EDIT: (id: string) => `/admin/expenses/${id}/edit`,
    EXPENSES_CATEGORIES: '/admin/expenses/categories',
    ACCOUNTING: {
      OVERVIEW: '/admin/accounting',
      MONTHLY: '/admin/accounting/monthly',
      QUARTERLY: '/admin/accounting/quarterly',
      YEARLY: '/admin/accounting/yearly',
    },
    POLICIES: {
      MAIN: '/admin/policies/overview',
      OVERVIEW: '/admin/policies/overview',
      SCHOOL_POLICIES: '/admin/policies/school-policies',
      SCHOOL_POLICIES_CREATE: '/admin/policies/school-policies/create',
      SCHOOL_POLICIES_EDIT: (id: string) => `/admin/policies/school-policies/${id}/edit`,
    },
    ANNOUNCEMENTS: '/admin/announcements',
    ANNOUNCEMENTS_CREATE: '/admin/announcements/create',
    DAILY_DIARY: '/admin/daily-diary',
    APP_ACCESS: {
      STAFF: '/admin/app-access/staff',
      PARENTS: '/admin/app-access/parents',
    },
    EXAMS: '/admin/exams',
    EXAMS_CREATE: '/admin/exams/create',
    EXAMS_VIEW: (id: string) => `/admin/exams/${id}`,
    EXAMS_EDIT: (id: string) => `/admin/exams/${id}`,
    EXAMS_RESULTS: (id: string) => `/admin/exams/${id}/results`,
  },
} as const;
